### ISSUE TITLE
Potential issues with Intel based processors/Intel dependency libraries

### ISSUE THREAD

**Issue by jjliupharmd** [njrhodes/ODA#2]
Error message in RStudio received while executing ODArun command:

_Fatal Error: This program was not built to run on the processor in your system.
The allowed processors are: Intel(R) processors with Swing New Instructions support.
Warning message:
In shell("megaoda.exe oda.pgm", intern = F) :
  'megaoda.exe oda.pgm' execution failed with error code 1  MegaODA.exe_ 

When executing MegaODA.exe in CMD prompt, here is a similar error message.  This was also replicated on a different machine with an AMD chip (different model).

_Fatal Error: This program was not built to run on the processor in your system.
The allowed processors are: Intel(R) processors with Swing New Instructions support._

**Comment by njrhodes** [comment]
Thanks for bringing this up. The issue appears to be with MEGAODA.exe not with the R code.

We do not maintain the MEGAODA code, but it is possibly due to a difference in the instruction sets. https://stackoverflow.com/questions/32168380/why-can-an-executable-run-on-both-intel-and-amd-processors

Closing this issue but adding a note to startup that AMD processors not supported. New version 1.1.1 with fix is now pushed.
